import { Hanken_Grotesk } from 'next/font/google';
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'], // Add other subsets if needed
  variable: '--font-hanken', // Optional: Define a custom CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
